TARGET := DeskCalc

SRC_CC := CalcApplication.cpp
SRC_CC += CalcOptions.cpp
SRC_CC += CalcView.cpp
SRC_CC += CalcWindow.cpp
SRC_CC += DeskCalc.cpp
SRC_CC += ExpressionTextView.cpp
SRC_CC += ExpressionParser.cpp
SRC_CC += InputTextView.cpp

OBJS := ${SRC_CC:.cpp=.o}

CPPFLAGS += -I.

$(TARGET) : $(OBJS)
